// examples/solid-example/src/index.tsx
import { createNavigationTree } from "@fiveway/core";
import { enableDevtools } from "@fiveway/devtools";
import { createActionHandler, NavigationProvider } from "@fiveway/solid";
/* @refresh reload */
import { render } from "solid-js/web";

import { Showcase } from "./Showcase.tsx";

const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error("Root element not found");
}

const fiveway = createNavigationTree();

Object.defineProperties(window, {
  FIVEWAY: { configurable: true, value: fiveway },
});

enableDevtools(fiveway);

function App() {
  createActionHandler(fiveway);
  return (
    <NavigationProvider tree={fiveway}>
      <Showcase />
    </NavigationProvider>
  );
}

render(App, root!);

// examples/react-example/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import { createNavigationTree } from "@fiveway/core";
import { NavigationProvider, useActionHandler, useSyncFocus } from "@fiveway/react";
import { enableDevtools } from "@fiveway/devtools";
import { Showcase } from "./Showcase.tsx";
import "./styles.css";
// import { Items } from "./Benchmark.tsx";

const navigationTree = createNavigationTree();

enableDevtools(navigationTree);

Object.defineProperties(window, {
  FIVEWAY: { configurable: true, value: navigationTree },
});

function App() {
  useActionHandler(navigationTree);
  useSyncFocus(navigationTree);
  return (
    <NavigationProvider tree={navigationTree}>
      <Showcase />
    </NavigationProvider>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
