// packages/fiveway-solid/src/element.tsx
import {
  chainedHandler,
  handleAction,
  spatialItemHandler,
  registerListener,
  type ChainedHandler,
  type NavigationAction,
  type NavigationTree,
} from "@fiveway/core";
import { defaultEventMapping, elementHandler } from "@fiveway/core/dom";
import { createEffect, createSignal, onCleanup } from "solid-js";

export type ElementHandler = ChainedHandler & {
  register: (e: HTMLElement | null) => void;
};

export function createElementHandler() {
  const [element, setElement] = createSignal<HTMLElement | null>(null);
  const position = () => element()?.getBoundingClientRect() ?? null;

  // handlers doen't need to be reactive
  const handler = chainedHandler([
    // eslint-disable-next-line solid/reactivity
    elementHandler(element),
    // eslint-disable-next-line solid/reactivity
    spatialItemHandler(position),
  ]) as ElementHandler;

  handler.register = setElement;

  return handler;
}

export type ActionHandlerOptions = {
  target?: EventTarget;
  eventToAction?: (e: Event) => NavigationAction | null;
};

export function createActionHandler(tree: NavigationTree, options: ActionHandlerOptions = {}) {
  createEffect(() => {
    const eventToAction = options.eventToAction ?? defaultEventMapping;
    const target = options.target ?? window;

    const handler = (e: Event) => {
      const action = eventToAction(e);
      if (action === null) {
        return;
      }

      handleAction(tree, action);
    };
    target.addEventListener("keydown", handler);

    onCleanup(() => {
      target.removeEventListener("keydown", handler);
    });
  });
}

export function useFocusSync(tree: NavigationTree) {
  createEffect(() => {
    const cleanup = registerListener(tree, "#", "focuschange", () => {
      const el = elementHandler.query(tree, tree.focus);
      if (el !== null) {
        el.focus();
      } else if (document.activeElement instanceof HTMLElement) {
        document.activeElement.blur();
      }
    });

    onCleanup(cleanup);
  });
}

// packages/fiveway-react/src/element.ts
import {
  type NavigationTree,
  type NavigationAction,
  type ChainedHandler,
  handleAction,
  chainedHandler,
  registerListener,
  spatialItemHandler,
} from "@fiveway/core";
import { defaultEventMapping, elementHandler } from "@fiveway/core/dom";
import { useRef, useMemo, useEffect } from "react";

export type ElementHandler = ChainedHandler & {
  register: (e: HTMLElement | null) => void;
};

export function useElementHandler(): ElementHandler {
  const elementRef = useRef<HTMLElement | null>(null);

  return useMemo(() => {
    const handler = chainedHandler([
      elementHandler(() => elementRef.current),
      spatialItemHandler(() => {
        return elementRef.current?.getBoundingClientRect() ?? null;
      }),
    ]) as ElementHandler;

    handler.register = (element) => {
      elementRef.current = element;
    };

    return handler;
  }, []);
}

export type ActionHandlerOptions = {
  target?: EventTarget;
  eventToAction?: (e: Event) => NavigationAction | null;
};

export function useActionHandler(
  tree: NavigationTree,
  options: ActionHandlerOptions = {},
): void {
  const eventToAction = options.eventToAction ?? defaultEventMapping;
  const target = options.target ?? window;

  useEffect(() => {
    const handler = (e: Event) => {
      const action = eventToAction(e);
      if (action === null) {
        return;
      }

      handleAction(tree, action);
    };

    target.addEventListener("keydown", handler);

    return () => {
      target.removeEventListener("keydown", handler);
    };
  }, [tree, target, eventToAction]);
}

export function useFocusSync(tree: NavigationTree): void {
  useEffect(() => {
    const handler = () => {
      const el = elementHandler.query(tree, tree.focus);
      if (el != null) {
        el.focus();
      } else if (document.activeElement instanceof HTMLElement) {
        document.activeElement.blur();
      }
    };

    return registerListener(tree, "#", handler);
  }, [tree]);
}
